IngressRoute:
  enable: true 
  selfSigned: true 
  url: "dev.rtrmotion.com"
  email: "email@hello.com" # will only be use if selfSigned is false
  # serviceName: "FastApi"
  # sevicePort: 8080
  httpMiddleware:
    scheme:
      redirectScheme:
        scheme: https
        permanent: true
  # httpsMiddleware:
    # auth:
    #   basicAuth:
    #     secret: secretName 
    # buffer:
    #   buffering:
    #     maxRequestBodyBytes: 2000000
    # prefix:
    #   addPrefix:
    #     prefix: /foo
