IngressRoute:
  enable: true 
  selfSigned: true 
  url: "dev.rtrmotion.com"
  connect:
    service: nginx 
    port: 8080 
  email: "email@hello.com" # will only be use if selfSigned is false
  httpMiddleware:
    scheme:
      redirectScheme:
        scheme: https
        permanent: true
    # auth:
    #   basicAuth:
    #     secret: secretName 
    # buffer:
    #   buffering:
    #     maxRequestBodyBytes: 2000000
    # prefix:
    #   addPrefix:
    #     prefix: /foo
  # https-middleware:
  #   - redirectScheme
  #   - addPrefix